////////////////////AUTOGENERATED XIB EXPORTED CODE - DO NOT ALTER////////////////////

#pragma once



inline CGRect getGeneratedViewTemplates_iPadFrame()
{
    return CGRectMake(0.0f, 0.0f, 320.0f, 568.0f);
}

inline void populateGeneratedViewTemplates_iPad( UIView** rootView, UIButton** variableNameButton, UIView** variableNameView, UIImageView** variableNameImage, UILabel** variableNameLabel )
{
	[(*rootView) setHidden:false];
	[(*rootView) setFrame:CGRectMake( 0.0f, 0.0f, 320.0f, 568.0f )];
	[(*rootView) setBackgroundColor:[UIColor colorWithRed:255 green:255 blue:255 alpha:255]];
	[(*rootView) setAutoresizingMask:UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight];
	[(*rootView) setAlpha:1.0f];
	[(*rootView) setClipsToBounds:false];
	[(*rootView) setContentMode:UIViewContentModeScaleToFill];

	(*variableNameButton) = [UIButton buttonWithType:UIButtonTypeRoundedRect];
	[(*variableNameButton) setTitleColor:[UIColor colorWithRed:56 green:84 blue:135 alpha:255] forState:UIControlStateNormal];
	[(*variableNameButton) setTitleColor:[UIColor colorWithRed:255 green:255 blue:255 alpha:255] forState:UIControlStateHighlighted];
	[(*variableNameButton).titleLabel setFont:[UIFont fontWithName:@".HelveticaNeueInterface-MediumP4" size:15.0f] ];
	[(*variableNameButton) setBackgroundImage:[UIImage imageNamed:@"backgroundImageDown.png"] forState:UIControlStateHighlighted];
	[(*variableNameButton) setEnabled:true];
	[(*variableNameButton) setBackgroundImage:[UIImage imageNamed:@"backgroundImage.png"] forState:UIControlStateNormal];
	[(*variableNameButton).titleLabel setNumberOfLines:1];
	[(*rootView) addSubview:(*variableNameButton)];

	(*variableNameView) = [ [UIView alloc] init];
	[(*variableNameView) setHidden:false];
	[(*variableNameView) setFrame:CGRectMake( 80.0f, 85.0f, 160.0f, 284.0f )];
	[(*variableNameView) setBackgroundColor:[UIColor colorWithRed:255 green:255 blue:255 alpha:255]];
	[(*variableNameView) setAutoresizingMask:UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin];
	[(*variableNameView) setAlpha:1.0f];
	[(*variableNameView) setClipsToBounds:false];
	[(*variableNameView) setContentMode:UIViewContentModeScaleToFill];
	[(*rootView) addSubview:(*variableNameView)];

	// Note: no image set for view
	(*variableNameImage) = [ [UIImageView alloc] init];
	[(*rootView) addSubview:(*variableNameImage)];

	(*variableNameLabel) = [ [UILabel alloc] init];
	[(*variableNameLabel) setLineBreakMode:NSLineBreakByTruncatingTail];
	[(*variableNameLabel) setAdjustsFontSizeToFitWidth:false];
	[(*variableNameLabel) setNumberOfLines:1];
	[(*variableNameLabel) setFont:[UIFont fontWithName:@".HelveticaNeueInterface-M3" size:17.0f] ];
	[(*variableNameLabel) setTextAlignment:NSTextAlignmentLeft];
	[(*variableNameLabel) setTextColor:[UIColor colorWithRed:0 green:0 blue:0 alpha:255]];
	[(*rootView) addSubview:(*variableNameLabel)];
}

inline void populatePreserveGeneratedViewTemplates_iPad( UIView** rootView, bool preserveTopLeft, bool preserveSize, UIButton** variableNameButton, UIView** variableNameView, UIImageView** variableNameImage, UILabel** variableNameLabel )
{
    CGRect preservedFrame = [ (*rootView) frame];

    populateGeneratedViewTemplates_iPad( rootView, variableNameButton, variableNameView, variableNameImage, variableNameLabel );
    CGRect generatedFrame = getGeneratedViewTemplates_iPadFrame();
    if ( !preserveTopLeft )
    {
    preservedFrame = CGRectMake( 
                        generatedFrame.origin.x,
                        generatedFrame.origin.y,
                        preservedFrame.size.width,
                        preservedFrame.size.height
                        );
    }

    if ( !preserveSize )
    {
    preservedFrame = CGRectMake( 
                        preservedFrame.origin.x,
                        preservedFrame.origin.y,
                        generatedFrame.size.width,
                        generatedFrame.size.height
                        );
    }
    if ( preserveTopLeft || preserveSize )
    {
        [ (*rootView) setFrame:preservedFrame];
    }
}

inline UIView* constructGeneratedViewTemplates_iPad( UIButton** variableNameButton, UIView** variableNameView, UIImageView** variableNameImage, UILabel** variableNameLabel )
{
    UIView* rootView = [ [UIView alloc] init];
    populateGeneratedViewTemplates_iPad( &rootView, variableNameButton, variableNameView, variableNameImage, variableNameLabel );
    return rootView;
}
