////////////////////AUTOGENERATED XIB EXPORTED CODE - DO NOT ALTER////////////////////
//
// Exported from ViewTemplates_Xcode5.xib
//

#pragma once



CGRect getGeneratedViewTemplates_Xcode5Frame()
{
    return CGRectMake(0.0f, 0.0f, 320.0f, 568.0f);
}

void populateGeneratedViewTemplates_Xcode5( UIView** rootView, UILabel** variableNameLabel, UIButton** variableNameButton1, UIButton** variableNameButton2, UIImageView** variableNameImage, UIView** variableNameView, UILabel** variableNameLabel2 )
{
	[(*rootView) setHidden:NO];
	[(*rootView) setFrame:CGRectMake( 0.0f, 0.0f, 320.0f, 568.0f )];
	[(*rootView) setBackgroundColor:[UIColor colorWithRed:1.0f green:1.0f blue:1.0f alpha:1.0f]];
	[(*rootView) setAutoresizingMask:UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight];
	[(*rootView) setAlpha:1.0f];
	[(*rootView) setClipsToBounds:NO];
	[(*rootView) setContentMode:UIViewContentModeScaleToFill];

	(*variableNameLabel) = [ [UILabel alloc] init];
	[(*variableNameLabel) setClipsToBounds:YES];
	[(*variableNameLabel) setHidden:NO];
	[(*variableNameLabel) setFrame:CGRectMake( 20.0f, 20.0f, 280.0f, 21.0f )];
	[(*variableNameLabel) setAlpha:1.0f];
	[(*variableNameLabel) setFont:[UIFont fontWithName:@".HelveticaNeueInterface-M3" size:17.0f] ];
	[(*variableNameLabel) setTextColor:[UIColor colorWithRed:0.0f green:0.0f blue:0.0f alpha:1.0f]];
	[(*variableNameLabel) setText:NSLocalizedString( @"Label", nil ) ];
	[(*variableNameLabel) setBackgroundColor:[UIColor colorWithRed:0.820136f green:1.0f blue:0.788757f alpha:1.0f]];
	[(*variableNameLabel) setLineBreakMode:NSLineBreakByTruncatingTail];
	[(*variableNameLabel) setTextAlignment:NSTextAlignmentCenter];
	[(*variableNameLabel) setContentMode:UIViewContentModeLeft];
	[(*variableNameLabel) setNumberOfLines:1];
	[(*variableNameLabel) setAdjustsFontSizeToFitWidth:NO];
	[(*variableNameLabel) setAutoresizingMask:UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin];
	[(*rootView) addSubview:(*variableNameLabel)];

	(*variableNameButton1) = [UIButton buttonWithType:UIButtonTypeRoundedRect];
	[(*variableNameButton1) setHidden:NO];
	[(*variableNameButton1) setFrame:CGRectMake( 124.0f, 49.0f, 73.0f, 29.0f )];
	[(*variableNameButton1) setAlpha:1.0f];
	[(*variableNameButton1) setTitleColor:[UIColor colorWithRed:0.0f green:0.478431f blue:1.0f alpha:1.0f] forState:UIControlStateHighlighted];
	[(*variableNameButton1) setTitle:NSLocalizedString( @"ButtonTitleLocalizationKey", nil ) forState:UIControlStateNormal ];
	[(*variableNameButton1).titleLabel setNumberOfLines:1];
	[(*variableNameButton1).titleLabel setFont:[UIFont fontWithName:@".HelveticaNeueInterface-M3" size:15.0f] ];
	[(*variableNameButton1) setEnabled:YES];
	[(*variableNameButton1) setBackgroundImage:[UIImage imageNamed:@"backgroundImageDown.png"] forState:UIControlStateHighlighted];
	[(*variableNameButton1) setTitleColor:[UIColor colorWithRed:0.0f green:0.478431f blue:1.0f alpha:1.0f] forState:UIControlStateNormal];
	[(*variableNameButton1) setBackgroundColor:[UIColor colorWithRed:0.964942f green:0.739116f blue:1.0f alpha:1.0f]];
	[(*variableNameButton1) setContentMode:UIViewContentModeScaleToFill];
	[(*variableNameButton1) setClipsToBounds:NO];
	[(*variableNameButton1) setAutoresizingMask:UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin];
	[(*rootView) addSubview:(*variableNameButton1)];

	(*variableNameButton2) = [UIButton buttonWithType:UIButtonTypeRoundedRect];
	[(*variableNameButton2) setHidden:NO];
	[(*variableNameButton2) setFrame:CGRectMake( 124.0f, 85.0f, 73.0f, 62.0f )];
	[(*variableNameButton2) setAlpha:1.0f];
	[(*variableNameButton2) setTitleColor:[UIColor colorWithRed:0.0f green:0.478431f blue:1.0f alpha:1.0f] forState:UIControlStateHighlighted];
	[(*variableNameButton2) setTitle:NSLocalizedString( @"ButtonTitleLocalizationKey", nil ) forState:UIControlStateNormal ];
	[(*variableNameButton2).titleLabel setNumberOfLines:1];
	[(*variableNameButton2).titleLabel setFont:[UIFont fontWithName:@".HelveticaNeueInterface-M3" size:15.0f] ];
	[(*variableNameButton2) setBackgroundImage:[UIImage imageNamed:@"Icon.png"] forState:UIControlStateNormal];
	[(*variableNameButton2) setEnabled:YES];
	[(*variableNameButton2) setBackgroundImage:[UIImage imageNamed:@"backgroundImageDown.png"] forState:UIControlStateHighlighted];
	[(*variableNameButton2) setTitleColor:[UIColor colorWithRed:0.0f green:0.478431f blue:1.0f alpha:1.0f] forState:UIControlStateNormal];
	[(*variableNameButton2) setBackgroundColor:[UIColor colorWithRed:0.988132f green:1.0f blue:0.745925f alpha:1.0f]];
	[(*variableNameButton2) setContentMode:UIViewContentModeScaleToFill];
	[(*variableNameButton2) setClipsToBounds:NO];
	[(*variableNameButton2) setAutoresizingMask:UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin];
	[(*rootView) addSubview:(*variableNameButton2)];

	(*variableNameImage) = [ [UIImageView alloc] init];
	[(*variableNameImage) setHidden:NO];
	[(*variableNameImage) setFrame:CGRectMake( 96.0f, 155.0f, 128.0f, 128.0f )];
	[(*variableNameImage) setBackgroundColor:[UIColor colorWithRed:0.0f green:0.0f blue:0.0f alpha:0.0f]];
	[(*variableNameImage) setImage:[UIImage imageNamed:@"Icon.png"] ];
	[(*variableNameImage) setAutoresizingMask:UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin];
	[(*variableNameImage) setAlpha:1.0f];
	[(*variableNameImage) setClipsToBounds:NO];
	[(*variableNameImage) setContentMode:UIViewContentModeScaleToFill];
	[(*rootView) addSubview:(*variableNameImage)];

	(*variableNameView) = [ [UIView alloc] init];
	[(*variableNameView) setHidden:NO];
	[(*variableNameView) setFrame:CGRectMake( 20.0f, 291.0f, 280.0f, 72.0f )];
	[(*variableNameView) setBackgroundColor:[UIColor colorWithRed:0.850851f green:0.802459f blue:1.0f alpha:1.0f]];
	[(*variableNameView) setAutoresizingMask:UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin];
	[(*variableNameView) setAlpha:1.0f];
	[(*variableNameView) setClipsToBounds:NO];
	[(*variableNameView) setContentMode:UIViewContentModeScaleToFill];

	(*variableNameLabel2) = [ [UILabel alloc] init];
	[(*variableNameLabel2) setClipsToBounds:YES];
	[(*variableNameLabel2) setHidden:NO];
	[(*variableNameLabel2) setFrame:CGRectMake( 0.0f, 26.0f, 280.0f, 21.0f )];
	[(*variableNameLabel2) setAlpha:1.0f];
	[(*variableNameLabel2) setFont:[UIFont fontWithName:@".HelveticaNeueInterface-M3" size:17.0f] ];
	[(*variableNameLabel2) setTextColor:[UIColor colorWithRed:0.0f green:0.0f blue:0.0f alpha:1.0f]];
	[(*variableNameLabel2) setText:NSLocalizedString( @"Label within View", nil ) ];
	[(*variableNameLabel2) setBackgroundColor:[UIColor colorWithRed:0.820136f green:1.0f blue:0.788757f alpha:1.0f]];
	[(*variableNameLabel2) setLineBreakMode:NSLineBreakByTruncatingTail];
	[(*variableNameLabel2) setTextAlignment:NSTextAlignmentCenter];
	[(*variableNameLabel2) setContentMode:UIViewContentModeLeft];
	[(*variableNameLabel2) setNumberOfLines:1];
	[(*variableNameLabel2) setAdjustsFontSizeToFitWidth:NO];
	[(*variableNameLabel2) setAutoresizingMask:UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin];
	[(*variableNameView) addSubview:(*variableNameLabel2)];
	[(*rootView) addSubview:(*variableNameView)];

	UIView* genericUIView0 = [ [UIView alloc] init];
	[genericUIView0 setHidden:NO];
	[genericUIView0 setFrame:CGRectMake( 20.0f, 371.0f, 280.0f, 54.0f )];
	[genericUIView0 setBackgroundColor:[UIColor colorWithRed:1.0f green:0.901406f blue:0.702651f alpha:1.0f]];
	[genericUIView0 setAutoresizingMask:UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin];
	[genericUIView0 setAlpha:1.0f];
	[genericUIView0 setClipsToBounds:NO];
	[genericUIView0 setContentMode:UIViewContentModeScaleToFill];
	[(*rootView) addSubview:genericUIView0];
}

void populatePreserveGeneratedViewTemplates_Xcode5( UIView** rootView, bool preserveTopLeft, bool preserveSize, UILabel** variableNameLabel, UIButton** variableNameButton1, UIButton** variableNameButton2, UIImageView** variableNameImage, UIView** variableNameView, UILabel** variableNameLabel2 )
{
    CGRect preservedFrame = [ (*rootView) frame];

    populateGeneratedViewTemplates_Xcode5( rootView, variableNameLabel, variableNameButton1, variableNameButton2, variableNameImage, variableNameView, variableNameLabel2 );
    CGRect generatedFrame = getGeneratedViewTemplates_Xcode5Frame();
    if ( !preserveTopLeft )
    {
    preservedFrame = CGRectMake( 
                        generatedFrame.origin.x,
                        generatedFrame.origin.y,
                        preservedFrame.size.width,
                        preservedFrame.size.height
                        );
    }

    if ( !preserveSize )
    {
    preservedFrame = CGRectMake( 
                        preservedFrame.origin.x,
                        preservedFrame.origin.y,
                        generatedFrame.size.width,
                        generatedFrame.size.height
                        );
    }
    if ( preserveTopLeft || preserveSize )
    {
        [ (*rootView) setFrame:preservedFrame];
    }
}

UIView* constructGeneratedViewTemplates_Xcode5( UILabel** variableNameLabel, UIButton** variableNameButton1, UIButton** variableNameButton2, UIImageView** variableNameImage, UIView** variableNameView, UILabel** variableNameLabel2 )
{
    UIView* rootView = [ [UIView alloc] init];
    populateGeneratedViewTemplates_Xcode5( &rootView, variableNameLabel, variableNameButton1, variableNameButton2, variableNameImage, variableNameView, variableNameLabel2 );
    return rootView;
}
