////////////////////AUTOGENERATED XIB EXPORTED CODE - DO NOT ALTER////////////////////

#pragma once



inline CGRect getGeneratedViewTemplatesFrame()
{
    return CGRectMake(0.0f, 0.0f, 320.0f, 568.0f);
}

inline void populateGeneratedViewTemplates( UIView** rootView, UILabel** variableNameLabel, UIButton** variableNameButton1, UIButton** variableNameButton2, UIImageView** variableNameImage, UIView** variableNameView, UILabel** variableNameLabel2 )
{
	[(*rootView) setHidden:false];
	[(*rootView) setFrame:CGRectMake( 0.0f, 0.0f, 320.0f, 568.0f )];
	[(*rootView) setBackgroundColor:[UIColor colorWithRed:255 green:255 blue:255 alpha:255]];
	[(*rootView) setAutoresizingMask:UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight];
	[(*rootView) setAlpha:1.0f];
	[(*rootView) setClipsToBounds:false];
	[(*rootView) setContentMode:UIViewContentModeScaleToFill];

	(*variableNameLabel) = [ [UILabel alloc] init];
	[(*variableNameLabel) setLineBreakMode:UILineBreakModeTailTruncation];
	[(*variableNameLabel) setAdjustsFontSizeToFitWidth:false];
	[(*variableNameLabel) setNumberOfLines:1];
	[(*variableNameLabel) setFont:[UIFont fontWithName:@".HelveticaNeueInterface-M3" size:17.0f] ];
	[(*variableNameLabel) setTextAlignment:UITextAlignmentCenter];
	[(*variableNameLabel) setMinimumFontSize:0.0f];
	[(*variableNameLabel) setTextColor:[UIColor colorWithRed:0 green:0 blue:0 alpha:255]];
	[(*rootView) addSubview:(*variableNameLabel)];

	(*variableNameButton1) = [UIButton buttonWithType:UIButtonTypeRoundedRect];
	[(*variableNameButton1) setTitleColor:[UIColor colorWithRed:56 green:84 blue:135 alpha:255] forState:UIControlStateNormal];
	[(*variableNameButton1) setTitleColor:[UIColor colorWithRed:255 green:255 blue:255 alpha:255] forState:UIControlStateHighlighted];
	[(*variableNameButton1).titleLabel setFont:[UIFont fontWithName:@".HelveticaNeueInterface-MediumP4" size:15.0f] ];
	[(*variableNameButton1) setBackgroundImage:[UIImage imageNamed:@"backgroundImageDown.png"] forState:UIControlStateHighlighted];
	[(*variableNameButton1) setEnabled:true];
	[(*variableNameButton1).titleLabel setMinimumFontSize:0.0f];
	[(*variableNameButton1).titleLabel setNumberOfLines:1];
	[(*rootView) addSubview:(*variableNameButton1)];

	(*variableNameButton2) = [UIButton buttonWithType:UIButtonTypeRoundedRect];
	[(*variableNameButton2) setTitleColor:[UIColor colorWithRed:56 green:84 blue:135 alpha:255] forState:UIControlStateNormal];
	[(*variableNameButton2) setTitleColor:[UIColor colorWithRed:255 green:255 blue:255 alpha:255] forState:UIControlStateHighlighted];
	[(*variableNameButton2).titleLabel setFont:[UIFont fontWithName:@".HelveticaNeueInterface-MediumP4" size:15.0f] ];
	[(*variableNameButton2) setBackgroundImage:[UIImage imageNamed:@"backgroundImageDown.png"] forState:UIControlStateHighlighted];
	[(*variableNameButton2) setEnabled:true];
	[(*variableNameButton2) setBackgroundImage:[UIImage imageNamed:@"Icon.png"] forState:UIControlStateNormal];
	[(*variableNameButton2).titleLabel setMinimumFontSize:0.0f];
	[(*variableNameButton2).titleLabel setNumberOfLines:1];
	[(*rootView) addSubview:(*variableNameButton2)];

	(*variableNameImage) = [ [UIImageView alloc] init];
	[(*variableNameImage) setImage:@"Icon.png"];
	[(*rootView) addSubview:(*variableNameImage)];

	(*variableNameView) = [ [UIView alloc] init];
	[(*variableNameView) setHidden:false];
	[(*variableNameView) setFrame:CGRectMake( 20.0f, 291.0f, 280.0f, 72.0f )];
	[(*variableNameView) setBackgroundColor:[UIColor colorWithRed:216 green:204 blue:255 alpha:255]];
	[(*variableNameView) setAutoresizingMask:UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin];
	[(*variableNameView) setAlpha:1.0f];
	[(*variableNameView) setClipsToBounds:false];
	[(*variableNameView) setContentMode:UIViewContentModeScaleToFill];

	(*variableNameLabel2) = [ [UILabel alloc] init];
	[(*variableNameLabel2) setLineBreakMode:UILineBreakModeTailTruncation];
	[(*variableNameLabel2) setAdjustsFontSizeToFitWidth:false];
	[(*variableNameLabel2) setNumberOfLines:1];
	[(*variableNameLabel2) setFont:[UIFont fontWithName:@".HelveticaNeueInterface-M3" size:17.0f] ];
	[(*variableNameLabel2) setTextAlignment:UITextAlignmentCenter];
	[(*variableNameLabel2) setMinimumFontSize:0.0f];
	[(*variableNameLabel2) setTextColor:[UIColor colorWithRed:0 green:0 blue:0 alpha:255]];
	[(*variableNameView) addSubview:(*variableNameLabel2)];
	[(*rootView) addSubview:(*variableNameView)];
}

inline void populatePreserveGeneratedViewTemplates( UIView** rootView, bool preserveTopLeft, bool preserveSize, UILabel** variableNameLabel, UIButton** variableNameButton1, UIButton** variableNameButton2, UIImageView** variableNameImage, UIView** variableNameView, UILabel** variableNameLabel2 )
{
    CGRect preservedFrame = [ (*rootView) frame];

    populateGeneratedViewTemplates( rootView, variableNameLabel, variableNameButton1, variableNameButton2, variableNameImage, variableNameView, variableNameLabel2 );
    CGRect generatedFrame = getGeneratedViewTemplatesFrame();
    if ( !preserveTopLeft )
    {
    preservedFrame = CGRectMake( 
                        generatedFrame.origin.x,
                        generatedFrame.origin.y,
                        preservedFrame.size.width,
                        preservedFrame.size.height
                        );
    }

    if ( !preserveSize )
    {
    preservedFrame = CGRectMake( 
                        preservedFrame.origin.x,
                        preservedFrame.origin.y,
                        generatedFrame.size.width,
                        generatedFrame.size.height
                        );
    }
    if ( preserveTopLeft || preserveSize )
    {
        [ (*rootView) setFrame:preservedFrame];
    }
}

inline UIView* constructGeneratedViewTemplates( UILabel** variableNameLabel, UIButton** variableNameButton1, UIButton** variableNameButton2, UIImageView** variableNameImage, UIView** variableNameView, UILabel** variableNameLabel2 )
{
    UIView* rootView = [ [UIView alloc] init];
    populateGeneratedViewTemplates( &rootView, variableNameLabel, variableNameButton1, variableNameButton2, variableNameImage, variableNameView, variableNameLabel2 );
    return rootView;
}
