////////////////////AUTOGENERATED XIB EXPORTED CODE - DO NOT ALTER////////////////////
//
// Exported from ViewTemplates_Xcode4.xib
//

#pragma once



CGRect getGeneratedViewTemplates_Xcode4Frame()
{
    return CGRectMake(0.0f, 0.0f, 320.0f, 568.0f);
}

void populateGeneratedViewTemplates_Xcode4( UIView** rootView, UILabel** variableNameLabel, UIButton** variableNameButton1, UIButton** variableNameButton2, UIImageView** variableNameImage, UIView** variableNameView, UILabel** variableNameLabel2 )
{
	[(*rootView) setHidden:NO];
	[(*rootView) setFrame:CGRectMake( 0.0f, 0.0f, 320.0f, 568.0f )];
	[(*rootView) setBackgroundColor:[UIColor colorWithRed:1.0f green:1.0f blue:1.0f alpha:1.0f]];
	[(*rootView) setAutoresizingMask:UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight];
	[(*rootView) setAlpha:1.0f];
	[(*rootView) setClipsToBounds:NO];
	[(*rootView) setContentMode:UIViewContentModeScaleToFill];

	(*variableNameLabel) = [ [UILabel alloc] init];
	[(*variableNameLabel) setTextColor:[UIColor colorWithRed:0.0f green:0.0f blue:0.0f alpha:1.0f]];
	[(*variableNameLabel) setLineBreakMode:NSLineBreakByTruncatingTail];
	[(*variableNameLabel) setAdjustsFontSizeToFitWidth:NO];
	[(*variableNameLabel) setNumberOfLines:1];
	[(*variableNameLabel) setTextAlignment:NSTextAlignmentCenter];
	[(*variableNameLabel) setFont:[UIFont fontWithName:@".HelveticaNeueInterface-M3" size:17.0f] ];
	[(*rootView) addSubview:(*variableNameLabel)];

	(*variableNameButton1) = [UIButton buttonWithType:UIButtonTypeRoundedRect];
	[(*variableNameButton1) setTitleColor:[UIColor colorWithRed:1.0f green:1.0f blue:1.0f alpha:1.0f] forState:UIControlStateHighlighted];
	[(*variableNameButton1).titleLabel setFont:[UIFont fontWithName:@".HelveticaNeueInterface-MediumP4" size:15.0f] ];
	[(*variableNameButton1) setBackgroundImage:[UIImage imageNamed:@"backgroundImageDown.png"] forState:UIControlStateHighlighted];
	[(*variableNameButton1) setEnabled:YES];
	[(*variableNameButton1).titleLabel setNumberOfLines:1];
	[(*variableNameButton1) setTitleColor:[UIColor colorWithRed:0.219608f green:0.329412f blue:0.529412f alpha:1.0f] forState:UIControlStateNormal];
	[(*rootView) addSubview:(*variableNameButton1)];

	(*variableNameButton2) = [UIButton buttonWithType:UIButtonTypeRoundedRect];
	[(*variableNameButton2) setTitleColor:[UIColor colorWithRed:1.0f green:1.0f blue:1.0f alpha:1.0f] forState:UIControlStateHighlighted];
	[(*variableNameButton2).titleLabel setFont:[UIFont fontWithName:@".HelveticaNeueInterface-MediumP4" size:15.0f] ];
	[(*variableNameButton2) setBackgroundImage:[UIImage imageNamed:@"backgroundImageDown.png"] forState:UIControlStateHighlighted];
	[(*variableNameButton2) setEnabled:YES];
	[(*variableNameButton2) setBackgroundImage:[UIImage imageNamed:@"Icon.png"] forState:UIControlStateNormal];
	[(*variableNameButton2).titleLabel setNumberOfLines:1];
	[(*variableNameButton2) setTitleColor:[UIColor colorWithRed:0.219608f green:0.329412f blue:0.529412f alpha:1.0f] forState:UIControlStateNormal];
	[(*rootView) addSubview:(*variableNameButton2)];

	(*variableNameImage) = [ [UIImageView alloc] init];
	[(*variableNameImage) setImage:[UIImage imageNamed:@"Icon.png"] ];
	[(*rootView) addSubview:(*variableNameImage)];

	(*variableNameView) = [ [UIView alloc] init];
	[(*variableNameView) setHidden:NO];
	[(*variableNameView) setFrame:CGRectMake( 20.0f, 291.0f, 280.0f, 72.0f )];
	[(*variableNameView) setBackgroundColor:[UIColor colorWithRed:0.850851f green:0.802459f blue:1.0f alpha:1.0f]];
	[(*variableNameView) setAutoresizingMask:UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin];
	[(*variableNameView) setAlpha:1.0f];
	[(*variableNameView) setClipsToBounds:NO];
	[(*variableNameView) setContentMode:UIViewContentModeScaleToFill];

	(*variableNameLabel2) = [ [UILabel alloc] init];
	[(*variableNameLabel2) setTextColor:[UIColor colorWithRed:0.0f green:0.0f blue:0.0f alpha:1.0f]];
	[(*variableNameLabel2) setLineBreakMode:NSLineBreakByTruncatingTail];
	[(*variableNameLabel2) setAdjustsFontSizeToFitWidth:NO];
	[(*variableNameLabel2) setNumberOfLines:1];
	[(*variableNameLabel2) setTextAlignment:NSTextAlignmentCenter];
	[(*variableNameLabel2) setFont:[UIFont fontWithName:@".HelveticaNeueInterface-M3" size:17.0f] ];
	[(*variableNameView) addSubview:(*variableNameLabel2)];
	[(*rootView) addSubview:(*variableNameView)];
}

void populatePreserveGeneratedViewTemplates_Xcode4( UIView** rootView, bool preserveTopLeft, bool preserveSize, UILabel** variableNameLabel, UIButton** variableNameButton1, UIButton** variableNameButton2, UIImageView** variableNameImage, UIView** variableNameView, UILabel** variableNameLabel2 )
{
    CGRect preservedFrame = [ (*rootView) frame];

    populateGeneratedViewTemplates_Xcode4( rootView, variableNameLabel, variableNameButton1, variableNameButton2, variableNameImage, variableNameView, variableNameLabel2 );
    CGRect generatedFrame = getGeneratedViewTemplates_Xcode4Frame();
    if ( !preserveTopLeft )
    {
    preservedFrame = CGRectMake( 
                        generatedFrame.origin.x,
                        generatedFrame.origin.y,
                        preservedFrame.size.width,
                        preservedFrame.size.height
                        );
    }

    if ( !preserveSize )
    {
    preservedFrame = CGRectMake( 
                        preservedFrame.origin.x,
                        preservedFrame.origin.y,
                        generatedFrame.size.width,
                        generatedFrame.size.height
                        );
    }
    if ( preserveTopLeft || preserveSize )
    {
        [ (*rootView) setFrame:preservedFrame];
    }
}

UIView* constructGeneratedViewTemplates_Xcode4( UILabel** variableNameLabel, UIButton** variableNameButton1, UIButton** variableNameButton2, UIImageView** variableNameImage, UIView** variableNameView, UILabel** variableNameLabel2 )
{
    UIView* rootView = [ [UIView alloc] init];
    populateGeneratedViewTemplates_Xcode4( &rootView, variableNameLabel, variableNameButton1, variableNameButton2, variableNameImage, variableNameView, variableNameLabel2 );
    return rootView;
}
