////////////////////AUTOGENERATED XIB EXPORTED CODE - DO NOT ALTER////////////////////
//
// Exported from $instanceName$.xib
//

#pragma once

$includes$

inline ofRectangle getGenerated$instanceName$Frame()
{
    return ofRectangle(∂frame.x∂, ∂frame.y∂, ∂frame.width∂, ∂frame.height∂);
}

inline void populateGenerated$instanceName$( ofPtr< ofxGenericView > rootViewﬁ )
{$GeneratedBody$}

inline void populateGeneratedMapped$instanceName$( ofPtr< ofxGenericView > rootView, ofPtr< ofxGenericValueStore > &outlets )
{
$IndividualOutletReferences$

    populateGenerated$instanceName$( rootView$PassForAssign$ );

    outlets = ofxGenericValueStore::create( ofxGenericValueStore::Object );
$OutletReferencesToMap$
}

inline void populatePreserveGenerated$instanceName$( ofPtr< ofxGenericView > rootView, bool preserveTopLeft, bool preserveSizeﬁ )
{
    ofRectangle preservedFrame = rootView->getFrame();

    populateGenerated$instanceName$( rootView∞ );
    ofRectangle generatedFrame = getGenerated$instanceName$Frame();
    if ( !preserveTopLeft )
    {
        preservedFrame.x = generatedFrame.x;
        preservedFrame.y = generatedFrame.y;
    }

    if ( !preserveSize )
    {
        preservedFrame.width = generatedFrame.width;
        preservedFrame.height = generatedFrame.height;
    }
    if ( preserveTopLeft || preserveSize )
    {
        rootView->setFrame( preservedFrame );
    }
}

inline ofPtr< ofxGenericView > constructGenerated$instanceName$( % )
{
    ofPtr< ofxGenericView > rootView = ofxGenericView::create();
    populateGenerated$instanceName$( rootView∞ );
    return rootView;
}
