////////////////////AUTOGENERATED XIB EXPORTED CODE - DO NOT ALTER////////////////////
//
// Exported from $instanceName$.xib
//

#pragma once

$includes$

inline CGRect getGenerated$instanceName$Frame()
{
    return CGRectMake(∂frame.x∂, ∂frame.y∂, ∂frame.width∂, ∂frame.height∂);
}

inline void populateGenerated$instanceName$( UIView** rootViewﬁ )
{$GeneratedBody$}

inline void populatePreserveGenerated$instanceName$( UIView** rootView, bool preserveTopLeft, bool preserveSizeﬁ )
{
    CGRect preservedFrame = [ (*rootView) frame];

    populateGenerated$instanceName$( rootView∞ );
    CGRect generatedFrame = getGenerated$instanceName$Frame();
    if ( !preserveTopLeft )
    {
    preservedFrame = CGRectMake( 
                        generatedFrame.origin.x,
                        generatedFrame.origin.y,
                        preservedFrame.size.width,
                        preservedFrame.size.height
                        );
    }

    if ( !preserveSize )
    {
    preservedFrame = CGRectMake( 
                        preservedFrame.origin.x,
                        preservedFrame.origin.y,
                        generatedFrame.size.width,
                        generatedFrame.size.height
                        );
    }
    if ( preserveTopLeft || preserveSize )
    {
        [ (*rootView) setFrame:preservedFrame];
    }
}

inline UIView* constructGenerated$instanceName$( % )
{
    UIView* rootView = [ [UIView alloc] init];
    populateGenerated$instanceName$( &rootView∞ );
    return rootView;
}
